# Obstacle feed mode (0 = sensor mode, 1 = OptiTrack mode, 2 = predefined obstacles)
# need to recompile after changing!
obstacle_feed_mode: 0

# Debugging info
activate_debug_output: true
activate_visualization: true

# Rate at which ellipse obstacles should be send out
update_rate: 10
discretization_steps: 25
prediction_horizon: 5

# Define the coordinate frames
frames:
    planning_frame: map             # For predefined obstacles
    robot_frame: odom          # For actual measured obstacles

publish:
    obstacles: ellipse_objects_feed
    obstacles_vis: visualize_ellipses_array
subscribe:
    detections: none #detection_3d
    optitrack: none #future_obj_track
    pedestrians: /spencer/perception/tracked_persons

# Detection criteria
detected_obstacles:
    distance_threshold: 10
    obstacle_threshold: 2
    min_obstacle_volume: 0.03
    max_obstacle_volume: 1.0
    obstacle_size: 0.3

# Create predefined obstacles
predefined_obstacles:
    pose_x: [85, 55]
    pose_y: [0, -1]
    heading: [0, 0]
    v_x: [-0.5, 0.15]
    v_y: [0.0, 0.0]
    dimensions:
        minor_semiaxis: [0.5, 0.5]
        major_semiaxis: [0.3, 0.3]
